/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as SidebarRouteRouteImport } from './../routes/_sidebar/route'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as SidebarProfileRouteImport } from './../routes/_sidebar/profile'
import { Route as SidebarSnapDetailsSnapIdRouteImport } from './../routes/_sidebar/snap-details.$snapId'
import { Route as SidebarMedicalDetailsCaseIdRouteImport } from './../routes/_sidebar/medical-details.$caseId'
import { Route as SidebarAssistanceDetailsCaseIdRouteImport } from './../routes/_sidebar/assistance-details.$caseId'

const SidebarRouteRoute = SidebarRouteRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarProfileRoute = SidebarProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarSnapDetailsSnapIdRoute =
  SidebarSnapDetailsSnapIdRouteImport.update({
    id: '/snap-details/$snapId',
    path: '/snap-details/$snapId',
    getParentRoute: () => SidebarRouteRoute,
  } as any)
const SidebarMedicalDetailsCaseIdRoute =
  SidebarMedicalDetailsCaseIdRouteImport.update({
    id: '/medical-details/$caseId',
    path: '/medical-details/$caseId',
    getParentRoute: () => SidebarRouteRoute,
  } as any)
const SidebarAssistanceDetailsCaseIdRoute =
  SidebarAssistanceDetailsCaseIdRouteImport.update({
    id: '/assistance-details/$caseId',
    path: '/assistance-details/$caseId',
    getParentRoute: () => SidebarRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof SidebarProfileRoute
  '/assistance-details/$caseId': typeof SidebarAssistanceDetailsCaseIdRoute
  '/medical-details/$caseId': typeof SidebarMedicalDetailsCaseIdRoute
  '/snap-details/$snapId': typeof SidebarSnapDetailsSnapIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof SidebarProfileRoute
  '/assistance-details/$caseId': typeof SidebarAssistanceDetailsCaseIdRoute
  '/medical-details/$caseId': typeof SidebarMedicalDetailsCaseIdRoute
  '/snap-details/$snapId': typeof SidebarSnapDetailsSnapIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_sidebar': typeof SidebarRouteRouteWithChildren
  '/_sidebar/profile': typeof SidebarProfileRoute
  '/_sidebar/assistance-details/$caseId': typeof SidebarAssistanceDetailsCaseIdRoute
  '/_sidebar/medical-details/$caseId': typeof SidebarMedicalDetailsCaseIdRoute
  '/_sidebar/snap-details/$snapId': typeof SidebarSnapDetailsSnapIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/assistance-details/$caseId'
    | '/medical-details/$caseId'
    | '/snap-details/$snapId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/assistance-details/$caseId'
    | '/medical-details/$caseId'
    | '/snap-details/$snapId'
  id:
    | '__root__'
    | '/'
    | '/_sidebar'
    | '/_sidebar/profile'
    | '/_sidebar/assistance-details/$caseId'
    | '/_sidebar/medical-details/$caseId'
    | '/_sidebar/snap-details/$snapId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SidebarRouteRoute: typeof SidebarRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SidebarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/profile': {
      id: '/_sidebar/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof SidebarProfileRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/snap-details/$snapId': {
      id: '/_sidebar/snap-details/$snapId'
      path: '/snap-details/$snapId'
      fullPath: '/snap-details/$snapId'
      preLoaderRoute: typeof SidebarSnapDetailsSnapIdRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/medical-details/$caseId': {
      id: '/_sidebar/medical-details/$caseId'
      path: '/medical-details/$caseId'
      fullPath: '/medical-details/$caseId'
      preLoaderRoute: typeof SidebarMedicalDetailsCaseIdRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/assistance-details/$caseId': {
      id: '/_sidebar/assistance-details/$caseId'
      path: '/assistance-details/$caseId'
      fullPath: '/assistance-details/$caseId'
      preLoaderRoute: typeof SidebarAssistanceDetailsCaseIdRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
  }
}

interface SidebarRouteRouteChildren {
  SidebarProfileRoute: typeof SidebarProfileRoute
  SidebarAssistanceDetailsCaseIdRoute: typeof SidebarAssistanceDetailsCaseIdRoute
  SidebarMedicalDetailsCaseIdRoute: typeof SidebarMedicalDetailsCaseIdRoute
  SidebarSnapDetailsSnapIdRoute: typeof SidebarSnapDetailsSnapIdRoute
}

const SidebarRouteRouteChildren: SidebarRouteRouteChildren = {
  SidebarProfileRoute: SidebarProfileRoute,
  SidebarAssistanceDetailsCaseIdRoute: SidebarAssistanceDetailsCaseIdRoute,
  SidebarMedicalDetailsCaseIdRoute: SidebarMedicalDetailsCaseIdRoute,
  SidebarSnapDetailsSnapIdRoute: SidebarSnapDetailsSnapIdRoute,
}

const SidebarRouteRouteWithChildren = SidebarRouteRoute._addFileChildren(
  SidebarRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SidebarRouteRoute: SidebarRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
